### ISSUE TITLE
How to create my own representation?

### ISSUE THREAD

**Issue by ademait** [nwxrichardson/aconite#61]
Hello, I'm Adem, I'm a PhD student and I have been using your tool to define the graphical notation of a BPMN extension.

First, congrats on the great work! I am currently working on extending BPMN and your tool is very useful. However, I find myself stucked when trying to create my own representation of the extension. 
I have created the emfatic file with the Aconite annotations, while generating the Odesign as described in the ReadME. But, when trying to create a new representation, I do not know how to proceed. 

I also took a look at the BPMN example you provide. So checking your example, if I want to create a new representation, using the Wizard I can select the "Business Process Diagram" model, as shown here:

![imatge](https://github.com/user-attachments/assets/452fc3ea-71cf-4893-b366-e913b01d0f5f)

However, when doing the same in my project, the resource does not appear. I tried by copying the resource from your project (uk.ac.york.aconite.bpmn), to mine, but it does not work.
 
![imatge](https://github.com/user-attachments/assets/e9d52bb6-690e-4a62-b5dc-d2d84067bf9c)

I tried finding some help on how I should proceed online without any luck. Could you give me a hand in here?

**Comment by nwxrichardson** [comment]
Hi Adem, 

You are correct a step is missing from the instructions if you are trying to follow this process with a new project. The `.aird` file needs to be made aware of the model, as in the example below and can be added by using the add button and selecting your model from the workspace.

![image](https://github.com/user-attachments/assets/e0100260-0af5-4ca0-a6cf-9455e039f631)

**Comment by ademait** [comment]
Hi @nwxrichardson , thank you for the fast response :)

I am not so familiar with Eclipse and Sirius. I think I am missing a step. In my case, how should I proceed to create the model? The `family.basicfamily` in your example. I have checked Sirius tutorials, but I have not found how to create it. Is there a place explaining how to do this step?

**Comment by ademait** [comment]
Hi @nwxrichardson , thank you for the clear step-by-step guidance. I could see what I was missing. I could create the model, so the issue is solved 😄
